ucldc/cinco

admin/cincoctrl/README.md
admin/cincoctrl/cincoctrl/contrib/__init__.py

add additional info and instructions to README

add additional info and instructions

---

.github/workflows/project_add_pr.yml

This auto-adds PRs to the A-Team Project Board w/ Status: Up next and Service: OAC

GH Workflow to add PRs to Project Board

---

arclight/README.md
arclight/app/controllers/catalog_controller.rb
arclight/lib/arclight/traject/ead2_component_config.rb
arclight/lib/arclight/traject/ead2_config.rb

add preview field and remove items with true from search results

add preview field and remove items with true from search results

---

cincoctrl/cincoctrl/templates/findingaids/attach_pdf.html
cincoctrl/cincoctrl/templates/findingaids/form.html
cincoctrl/cincoctrl/templates/findingaids/list_records.html

remove references to old template tag

remove references to old template tag

---

infrastructure/cinco/config/stage/cincoctrl/app.yaml

As per our discussion yesterday. This is already deployedd to stage

Update tg health check endpoint for ctrl

---

arclight/config/repositories.yml

add repositories list from cincoctrl

add repositories list from cincoctrl

---

cincoctrl/.envs/.local/.django
cincoctrl/config/settings/base.py
cincoctrl/config/settings/local.py
cincoctrl/config/settings/production.py

use env variables for settings
move into base so available to all setups
there will need to be another change to the templates to set the correct arclight url in stage/prd

move settings into base and use env variables

---

cincoctrl/cincoctrl/findingaids/signals.py
cincoctrl/cincoctrl/findingaids/urls.py
cincoctrl/cincoctrl/findingaids/views.py
cincoctrl/cincoctrl/templates/findingaids/queued.html
cincoctrl/cincoctrl/templates/findingaids/record.html
cincoctrl/config/settings/local.py

- Use the dag_run_conf in job_trigger, it is serialized correctly.
- Fill in update status code for "Preview" and "Publish" buttons
(I'm not sure I understand why both JobRun and JobTrigger descend from Job but maybe something specific to airflow)

dag run conf for JobRun isn't working

---

arclight/bin/index-from-s3

Preview flag isn't making it into solr. Fix arg number based on usage info.

fix preview arg

---

cincoctrl/cincoctrl/findingaids/tests.py
cincoctrl/cincoctrl/templates/findingaids/express_record.xml

- Fix language encoding in express record
- test
- Remove old typo from express record

Fix express language

---

dags/arclight_operator.py

Preview is always evaluating to false here now but the print for logging doesn't seem to be showing up anywhere.  Did a little research looks like this logging method should work.

fix logging in ECSOperator

---

arclight/bin/index-from-s3
cincoctrl/cincoctrl/findingaids/models.py
cincoctrl/cincoctrl/findingaids/signals.py
dags/arclight_operator.py
dags/index_finding_aid.py

- As recommend by Amy change the preview arg to a string and just pass it along to the indexing shell script, then test.
- fix oversight where status was not actually getting updated on indexing completion.

231 fix preview again

---

cincoctrl/cincoctrl/findingaids/models.py
cincoctrl/cincoctrl/findingaids/signals.py
cincoctrl/cincoctrl/templates/findingaids/record.html

- log index triggering
- make sure publish/preview flag works for other starting statuses
- update status correctly
- make preview/publish buttons visible for all statuses

fix preview status management

---

arclight/Gemfile
arclight/Gemfile.lock
arclight/config/initializers/logging.rb

Lograrge will transform Rails noisy logs into a single line of JSON

Add lograge for better logging

---

arclight/app/controllers/catalog_controller.rb

We don't want them so just disable them

Remove bookmarks from nav, search and record pages

---

.pre-commit-config.yaml
arclight/Gemfile
arclight/Gemfile.lock
arclight/app/controllers/catalog_controller.rb
arclight/app/helpers/application_helper.rb
arclight/app/models/search_builder.rb
arclight/app/models/user.rb
arclight/config/initializers/devise.rb
arclight/config/routes.rb
arclight/db/migrate/20241204213613_add_devise_guests_to_users.rb
arclight/db/schema.rb
arclight/lib/arclight/traject/ead2_component_config.rb
arclight/lib/arclight/traject/ead2_config.rb
arclight/lib/oac/normalized_component_title.rb
arclight/lib/oac/optional_year_range.rb
arclight/lib/oac/text_file_reader.rb

Add rubocop to pre-commit config and apply it's fixes to the ruby codebase.

Add rubocop to pre-commit and apply

---

cincoctrl/cincoctrl/templates/findingaids/express_record.xml

add media url

---

cincoctrl/cincoctrl/findingaids/management/commands/import_ead.py
cincoctrl/cincoctrl/findingaids/management/commands/import_record_express.py
cincoctrl/cincoctrl/findingaids/utils.py

apply changes made to import record express to import ead

Ead import prep

---

arclight/app/components/header_component.html.erb

Default to grouped search results

---

arclight/README.md
arclight/app/components/arclight/constraints_component.html.erb
arclight/app/controllers/arclight/repositories_controller.rb
arclight/app/helpers/application_helper.rb
arclight/app/views/arclight/repositories/_repository.html.erb
arclight/app/views/arclight/repositories/index.html.erb
arclight/config/locales/arclight.en.yml
arclight/spec/components/collection_tabs_component_spec.rb
arclight/spec/helpers/application_helper_spec.rb

- Make repo listing a to z list
- Make repository-limited search the main repository landing page
- Other minor tweaks to match wireframes

268 repos atoz

---

cincoctrl/cincoctrl/templates/findingaids/form.html

Updated descriptive intro text on submit EAD file page

Update description on submit EAD file page

---

cincoctrl/cincoctrl/templates/findingaids/list_records.html

Updated the headings on this page (and added new headings), updated the page description, and added links to point to submit EAD files & create RecordEXPRESS guides.

Updated descriptive text and added links on "manage collections" page

---

arclight/app/components/arclight/constraints_component.html.erb
arclight/app/components/hidden_facet_component.rb
arclight/app/components/online_content_facet_component.html.erb
arclight/app/components/online_content_facet_component.rb
arclight/app/controllers/catalog_controller.rb
arclight/app/views/arclight/repositories/_repository.html.erb
arclight/app/views/catalog/_search_button_component.html.erb
arclight/config/locales/arclight.en.yml

- Add repository search box
- Use toggle component for online access facet
- Remove bookmark and view type components 
- Update facet labeling and ordering

288 search results

---

arclight/app/views/arclight/repositories/_repository.html.erb
arclight/config/repositories.yml

- Remove translate tag from repo name (it was messing them up)
- Remove bad character

410 fix repo names

---

cincoctrl/cincoctrl/findingaids/management/commands/import_ead.py
cincoctrl/cincoctrl/findingaids/parser.py
cincoctrl/cincoctrl/findingaids/tests/test_parser.py

- no longer queue index on file import
- update eadid to the filename on import
- require values in required fields
- fix bug where level=collection wasn't flagged in the top component

459 446 import errors

---

arclight/bin/bulk-index-from-s3
arclight/bin/index-from-s3
cincoctrl/cincoctrl/findingaids/management/commands/bulk_index_finding_aids.py

Fix 2 indexing bugs
1. Finding aid list was being re-evaluated every pass of the loop, make it static
2. Quote EADID in command line because it may have spaces

469 fix bugs

---

cincoctrl/cincoctrl/findingaids/management/commands/import_ead.py
cincoctrl/cincoctrl/findingaids/parser.py
cincoctrl/cincoctrl/findingaids/tests/test_parser.py

- Clean up import output
- Fix bug in ark parsing where some characters could be cut off

Etl cleanup

---

arclight/config/repositories-stage.yml
arclight/config/repositories.yml
cincoctrl/cincoctrl/findingaids/management/commands/bulk_index_finding_aids.py
cincoctrl/cincoctrl/findingaids/models.py
cincoctrl/config/settings/production.py
cincoctrl/config/settings/stage.py
dags/arclight_operator.py
dags/cincoctrl_operator.py
infrastructure/cinco/config/prd/solr/solr-follower-1.yaml
infrastructure/cinco/config/prd/solr/solr-follower-2.yaml
infrastructure/cinco/config/stage/arclight/app.yaml

Additional changes required to make -stage vs. -prd switches in Airflow.

Multi stack dag

---

arclight/app/views/static_pages/about.html.erb
arclight/app/views/static_pages/help.html.erb
arclight/app/views/static_pages/quickstart.html.erb

Copy edits on FAQ, About, and Quick Start pages.

Copy edits on FAQ, About, and QuickStart

---

arclight/app/views/shared/_footer.html.erb
arclight/app/views/static_pages/help.html.erb
arclight/app/views/static_pages/quickstart.html.erb

Adding a link to the footer (quick start guide) & updating the quick start guide with some line breaks.

Footer update & video embed page update

---

arclight/Gemfile
arclight/Gemfile.lock
arclight/README.md
arclight/app/components/static_finding_aid/document_component.html.erb
arclight/app/views/static_finding_aid/_show_main_content.html.erb
arclight/config/cache.yml
arclight/config/database.yml
arclight/config/environments/development.rb
arclight/config/environments/production.rb
arclight/db/migrate/20250709213614_create_cache.rb
arclight/db/schema.rb
arclight/lib/oac/finding_aid_tree_node.rb
arclight/lib/tasks/cache.rake

Adds Solid Cache, a rails maintained cache backend that uses the DB for cache. So this includes migrations.
Utils to generate cache from the CLI or clear cache.

Cache for static finding aids.

---

arclight/config/repositories-stage.yml
arclight/config/repositories.yml
cincoctrl/cincoctrl/findingaids/management/commands/import_ead.py

- Update repo files to match repos available in arclight to what is available in cincoctrl
- Prd includes repos removed based on review from Adrian and Gabriela
- Minor addition to ead import output

update repositories config files for current state of servers

---

arclight/app/views/static_pages/help.html.erb

Adding some div's because the images are way too big.

Update help.html.erb - image divs

---

arclight/app/controllers/static_finding_aid_controller.rb
arclight/lib/oac/finding_aid_tree_node.rb
arclight/lib/tasks/cache.rake

Make many caches per finding aid, and then clear them out later.
Remove all facet stuff from static finding aid controller.

Revert to many caches per static finding aid

---

arclight/app/components/arclight/collection_sidebar_component.html.erb
arclight/config/repositories-stage.yml
arclight/config/repositories.yml
cincoctrl/cincoctrl/templates/users/repositories.yml

I added a class to the flatfile for website links - both to the generated flatfiles and to the template. @everreau - does this work without adding any complications to ETL of the repositories?

563 offsite links

---

arclight/app/controllers/arclight/repositories_controller.rb
arclight/app/controllers/arks_controller.rb
arclight/config/routes.rb
arclight/spec/requests/institutions_spec.rb

* Detailed Help
* Collection Guides
* Institution Landing Pages
* METS pages -> Calisphere
Related to #464

Add redirects from OAC4 for

---

arclight/app/controllers/arclight/repositories_controller.rb

- Not all the institution counts were showing on the A to Z page because we have too many!

set the facet limit higher because we have so many institutions

---

arclight/config/locales/arclight.en.yml

Updating "Other finding aids" to "Additional collection guides" & adding in "related" to tweak it to "Related resources"

Update arclight.en.yml - label updates

---

infrastructure/cinco/config/prd/cincoctrl/app.yaml
infrastructure/cinco/config/stage/cincoctrl/app.yaml

add arclight url for cincoctrl to link to previews

add arclight url for cincoctrl to link to previews

---

cincoctrl/cincoctrl/findingaids/models.py

use the right url

---

cincoctrl/cincoctrl/findingaids/management/commands/import_dublincore.py

fixes problem where headings were all applied to only a few records

get the finding aid earlier

---

arclight/app/controllers/arclight/repositories_controller.rb
arclight/app/controllers/catalog_controller.rb
arclight/app/controllers/static_finding_aid_controller.rb
arclight/app/models/concerns/cache_control.rb

Also adds in support for unknown institutions being redirected.

Set 7 days expiry for search and show pages

---

arclight/app/helpers/application_helper.rb
arclight/config/initializers/static_finding_aid.rb

Add feature to disallow links to specifric finding aids

---

arclight/config/routes.rb

This reverts commit 673f46d05cdd82ca1ed1c46eb58fa60cd617e165.

Revert "Make sure all styles of old URL come through"

---

arclight/app/components/header_component.html.erb

Reverting the sitewide banner to the OAC launch announcement.

Update sitewide banner

---

arclight/config/repositories-stage.yml

Adding NASA Armstrong Flight Research Center as a  new OAC repository

New repository

---

arclight/config/repositories-stage.yml

Verifying change to NASA Armstrong Flight Research Center's profile (e-mail, phone updates) on -stg first. Also testing the process of updating the repo YML file.

Verifying change to repository profile, on -stg

---

arclight/config/repositories.yml

Updated contact info for NASA Armstrong Flight Research Center, this time on prod. Also includes a new UCI repository

Update to NASA repo contact info + new UCI repo

---

arclight/config/repositories.yml

Update repositories yml (Adding in UCI Aeon)

Update repositories yml
