infrastructure/cinco/config/admin/app-servers.yaml, infrastructure/cinco/config/admin/db.yaml, infrastructure/cinco/config/arclight/solr-efs.yaml, infrastructure/cinco/config/arclight/solr-writer.yaml, infrastructure/cinco/config/arclight/solr.yaml, infrastructure/cinco/templates/ecs-webapp.j2, infrastructure/cinco/templates/efs.yaml, infrastructure/cinco/templates/rds-postgres.yaml
Creates Solr and Solr Writer ECS services talking to the same EFS volume. Limits HTTP(S) access to these services at the security group layer to the groups listed in `sceptre_user_data.HttpAccessList`
Still todo:
- script to create solr cores
=> Add Solr Infrastructure

.github/workflows/dags_test.yml, arclight/bin/index-from-s3, cincoctrl/cincoctrl/findingaids/management/commands/poll_sqs.py, dags/.airflowignore, dags/cincoctrl_operator.py, dags/dags_tests.py, dags/poll_message_queue.py, infrastructure/cinco/config/dags-deploy.yaml, infrastructure/cinco/config/stage/cincoctrl/build.yaml, infrastructure/cinco/config/stage/solr/build.yaml, infrastructure/cinco/templates/codebuild.j2
This PR:
- adds infrastructure to deploy Cinco-related DAGS to our existing MWAA instance. 
- updates the CincoCtrlEcsOperator's container name, task definition, security group, and logging configuration to resolve errors in this environment
- updates the CincoCtrl `manage.py poll_sqs` command to give output even when there are no messages on the queue to process. 
For this update, I made the following resources in clickops: 
- A cinco-dags-sync policy allowing uploads to the bucket where we store our PAD airflow DAGS. I wasn't quite sure if this belonged here in this repository, or with the pad-airflow cloudformation. There is a similar rikolti-dags-sync policy, but I couldn't find it in any of our repositories and I'm not sure if it's part of our existing cloudformation. 
- An addition …
=> Cinco DAGS development

dags/arclight_operator.py
Preview parameter is being passed into airflow correctly but it's not making it to the indexing process correctly.
I'm not 100% sure this fix is correct.
I think what's going on is that it's being cast to a string in `index_finding_aid` then we're testing it here as if it's still a boolean.
`preview="{{ params.preview }}",`
I could be wrong because there might be some airflow-specific magic going on here. I actually wouldn't expect this syntax to print the value of the variable to a string at all which gives me some doubt.
I also added some specific logging to get more info in case this doesn't work.
=> fix preview parameter passing 

cincoctrl/cincoctrl/airflow_client/management/commands/poll_airflow.py
- We're getting a ton of indexing histories for failed jobs so only poll the running jobs.  This seems like just an oversight to me.
=> only poll running jobs

cincoctrl/cincoctrl/findingaids/management/commands/prepare_finding_aid.py
- encode record express output as utf-8 before writing to file.  s3 fails to write if there are unicode characters otherwise.
=> encode utf-8 before writing out file, else it fails

cincoctrl/cincoctrl/airflow_client/management/commands/poll_airflow.py
I did mess up the status updating of index jobs with my last PR.  I didn't realize that this is the process that initially creates jobrun objects so jobtriggers that don't have a job run need to be included.
=> fix so triggers without job run objects can be updated

dags/poll_message_queue.py
Increase the rate that we're polling the textract job status.  With a large number of imports it's getting super behind only processing 10/hour. We may want to dial it back when we have other traffic happening.
=> increase the textract job polling rate

cincoctrl/cincoctrl/findingaids/admin.py, cincoctrl/cincoctrl/findingaids/management/commands/import_ead.py
- Tweak admin filters
- Fix bug where extref elements without href tags caused an uncaught error
- Fix bug where collection title was too long (this is a temporary fix, I guess we need to change this field to a text field)
- Add a general catch statement so unexpected errors don't abort the entire import
=> Fix ead import errors

arclight/lib/arclight/traject/ead2_config.rb
set solr commit to false.
during imports we're getting a lot of index failures because it's unable to commit at the end. queue up indexes and wait for the background process to commit everything.
=> set solr commit to false

arclight/app/controllers/arclight/repositories_controller.rb, arclight/app/controllers/catalog_controller.rb, arclight/config/downloads.yml
- Point XML links to s3 (we probably need to make this an env variable or something, also, on file upload we'll need to make sure the s3 file name is in the eadid field)
- By adding preview=false to the default_solr_query that meant that we were blocking the content list form loading for previewed items.  Instead add the preview=false to all the field-based queries
- Override the repositories controller so that counts and non-search-based item lists don't include previewed items
Previewed items are still showing up in the auto-complete drop-down.  I'm not sure yet how to fix this.
=> 247 preview bugs

arclight/app/components/oac/search_document_component.rb
Search bar on document display searches within the document's collection, not within the document. On component display pages, the search bar was setting `Collection: document`, which wasn't returning any results.
=> Arclight: always search within doc's collection, not document itself

arclight/app/components/arclight/document_component.html.erb
Access and Use displays the combination of collection-level restrictions and component-level restrictions on component pages. We'd like for it to display only the component-level restrictions on component pages, but this will require overwriting the access and use component. For now, add it back on every page.
=> Arclight: add access and use back everywhere

cincoctrl/cincoctrl/findingaids/models.py
we don't need to use the full path to the ead file in the eadid because we already know it and it's in the arclight base url.
=> we don't need the path in the eadid

arclight/app/components/static_finding_aid/document_component.rb
Was seeing errors in stage like
```
ActionView::Template::Error (undefined method `search_state' for #<StaticFindingAid::DocumentComponent
```
But was unable to reproduce locally. 
So stubbing in a method into the StaticFindingAids  DocumentComponent, as I don't think search_service is actually required there.
=> Document component shoud support search state?

arclight/app/components/static_finding_aid/document_component.rb, arclight/app/controllers/arks_controller.rb, arclight/app/controllers/static_finding_aid_controller.rb, arclight/config/routes.rb
but also stop tracking searches in the static finding aid controller.
Updates the canonical URL for static guides to findaid/static/ but includes a redirect for `*/entire_text` style path as well.
=> Add static finding aids as resource

cincoctrl/config/settings/production.py, dags/arclight_operator.py, dags/bulk_index_finding_aids.py, dags/cincoctrl_operator.py, dags/index_finding_aid.py, dags/poll_airflow_api.py, dags/poll_message_queue.py, infrastructure/cinco/config/prd/cincoctrl/app.yaml
As long as there are no issues with dynamically assigning some of these arguments on `__init__`, I think this actually will take care of all our stack issues (including even reporting back runtime state to CincoCtrl!). I could maybe change the variable names to 'stack_name' instead of 'version'.
=> DAGs: add stage vs. prod switch for cincoctrl op & arclight op

arclight/solr/conf/solrconfig.xml
This is slow and is blocking the solr server from coming up.
https://solr.apache.org/guide/solr/latest/query-guide/suggester.html
=> Don't build suggesst on startup of solr

arclight/app/helpers/application_helper.rb, arclight/app/views/catalog/show.html.erb, arclight/config/initializers/static_finding_aid.rb
Set as an env variable so we can tweak easier.
=> Don't show links to larger static finding aids

.github/workflows/versioned_release.yml, infrastructure/cinco/config/config.yaml, infrastructure/cinco/config/prd/arclight/app.yaml, infrastructure/cinco/config/prd/arclight/build.yaml, infrastructure/cinco/config/prd/cincoctrl/app.yaml, infrastructure/cinco/config/prd/cincoctrl/build.yaml, infrastructure/cinco/config/prd/solr/build.yaml, infrastructure/cinco/config/prd/solr/solr-follower-1.yaml, infrastructure/cinco/config/prd/solr/solr-follower-2.yaml, infrastructure/cinco/config/prd/solr/solr.yaml, infrastructure/cinco/scripts/message_slack.py
1) Adds a Github Workflow to create a new version release: 
- workflow uses yq to update `sceptre_user_data.cinco_version` in root sceptre config file
- creates a new commit on the target branch provided (default main)
- tags that branch and pushes both the new commit and the tag up to github
- cuts a new release using auto-generated release notes
2) Adds Slack message output to the codebuild process sending quicklinks to the Service's Tasks, Logs, and Deployments just before beginning --force-new-deployment
=> Build process sparkles

arclight/app/components/arclight/constraints_component.rb, arclight/app/components/arclight/online_content_filter_component.html.erb, arclight/app/components/header_component.rb, arclight/app/components/oac/search_document_component.rb, arclight/app/views/catalog/show.html.erb, arclight/app/views/static_pages/home.html.erb
oac-stg.cdlib.org is flagged with a security warning in Chrome because the form actions go to http://oac-stg.cdlib.org instead of https://oac-stg.cdlib.org. I had, in another commit, converted `search_action_url` to `search_action_path` and had expected that to be enough for rails to use the relative path.
=> Update search form to be relative [arclight]

arclight/app/views/arclight/requests/_aeon_web_ead.html.erb
if eadid isn't a file reference don't show aeon request
=> if eadid isn't a file reference don't show aeon request

arclight/app/controllers/arclight/repositories_controller.rb, arclight/app/controllers/static_pages_controller.rb
For most, follow the one week headers, but for the institution browse page, just a day so that changes are reflected when updates happen.
=> Add more cache control to controllers

arclight/app/controllers/static_finding_aid_controller.rb, arclight/config/initializers/static_finding_aid.rb
Lower the threshold for "large"
=> Redirect large static guides to the arclight guide page.

arclight/app/controllers/catalog_controller.rb, arclight/app/models/concerns/cache_control.rb, arclight/app/views/layouts/blacklight/base.html.erb, arclight/config/initializers/deprecation.rb, arclight/config/initializers/logging.rb, arclight/public/robots.txt
Turns off tracking from search links.
Disabe Turbo LxiiInks so that pages do not pre-load when a link is voered as tat requires js changes. Maybe we can turn it back on later.
Add caching for hierarchy requests.
Hopefuly silence some deprecation warnings?!?
Removes some leftover cruft static finding aid cruft.
Add a robots.txt too!
=> Removes tracking from search links

arclight/app/controllers/static_finding_aid_controller.rb
Without the return statements, Rails tells us:
```
AbstractController::DoubleRenderError (Render and/or redirect were called multiple times in this action. Please note that you may only call render OR redirect, and at most once per action. Also note that neither redirect nor render terminate execution of the action, so if you want to exit an action after redirecting, you need to do something like "redirect_to(...); return".):
```
=> Add return statements

.pre-commit-config.yaml
Exclude repositories.yml and repositories-stage.yml from end of file fixer (these files, when generated via cincoctrl, include a new line at the bottom).
=> update pre-commit-config to exclude repositories config

infrastructure/cinco/templates/codebuild.j2
=> Add lifecycle policies for untagged ECR images

arclight/app/controllers/application_controller.rb, arclight/app/controllers/errors_controller.rb
I'm seeing a lot of 406 errors in the log, and format is typically HTML, which Rails should have no problem dealing with. I don't actually see the request in the logs, though, so I wonder if Rails is doing something funky in its conversion of the Accepts header to format. 
I'm seeing some 406 errors for the ErrorsController, even, so I also made explicit where to find the not_found template. Rails shouldn't actually need this, but I wonder if it helps? 
This is related to card #830
=> 406 error investigation
